Modules/Admin/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::prefix('xi-admin')->name('admin.')->group(function() {

    Route::get('/', 'LoginController@index')->name('admin_home');
    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/doLogin', 'LoginController@doLogin')->name('doLogin');

    Route::middleware(['CHECK_ADMIN_LOGIN'])->group(function() {

        Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');
        Route::get('/logout', 'LoginController@logout')->name('logout');

        Route::match(['get', 'post'], '/profile', 'UserController@adminProfile')->name('profile');
    });

});

Modules/Admin/Http/Controllers/AdminController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('admin::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('admin::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('admin::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('admin::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Admin/Http/Controllers/DashboardController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function dashboard()
    {
        return view('admin::index');
    }
}

Modules/Admin/Http/Controllers/LoginController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function __construct()
    {
        $this->middleware('CHECK_ADMIN_GUEST')->except('logout');
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('admin::auth.login');
    }

    public function doLogin(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email'    => 'required',
            'password' => 'required'
        ]);

        if ($validator->fails()) {
            echo "val fail";
        } else {
            if (Auth::guard('admin')->attempt(['email' => $request->email, 'password' => $request->password, 'deleted_at' => NULL])) {
                $XI_ADMIN = Auth::guard('admin')->user();
                return redirect()->route('admin.dashboard');
                // implement GUser later.
            } else {
                return redirect()->route("admin.login");
            }
        }
        
    }

    public function logout()
    {
        if(Auth::guard('admin')->check()) {
            Auth::guard('admin')->logout();
        }

        return redirect()->route("admin.login");
    }
}

Modules/Admin/Http/Controllers/UserController.php
<?php

namespace Modules\Admin\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Request $r)
    {
        $this->userModel = new User;
    }

    /**
     * Returns profile view and updates admin profile.
     * @param Request $r
     * @return View/void
     * @author Mahiman Parmar
     */
    public function adminProfile(Request $r)
    {
        // *********************************
        // Code for updating the profile
        // *********************************
        if ($r->isMethod('post')) {
            //
        }

        // *********************************
        // Code to return profile view
        // *********************************
        if ($r->isMethod('get')) {
            return view("admin::users.profile");
        }
    }

    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('admin::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('admin::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('admin::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('admin::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Admin/Resources/views/index.blade.php
@extends('admin::layouts.master')

@section('title', 'Dashboard')

@section('page-header')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page-content')
<section class="content">
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h2 class="card-title">Dashboard</h2>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body">
            <h4>Welcome back, {{ XI_ADMIN()->name }}</h4>
        </div>
    </div>
</section>
@endsection

Modules/Admin/Resources/views/layouts/includes/bottom-layout.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> {{ env('ADMIN_VERSION') }}
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="http://xtremis.in">Xtremis Infotech</a>.</strong> All rights
    reserved.
</footer>

Modules/Admin/Resources/views/layouts/includes/css.blade.php
<link rel="stylesheet"
    href="{{ asset('admin-assets/plugins/fontawesome-free/css/all.min.css') }}">
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="{{ asset('admin-assets/dist/css/adminlte.min.css') }}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

<link rel="icon" href="{{ asset('front-assets/images/favicon.ico') }}" type="image/gif" sizes="16x16">

@yield('additional-css')

Modules/Admin/Resources/views/layouts/includes/javascript.blade.php
<script src="{{ asset('admin-assets/plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}">
</script>
<script src="{{ asset('admin-assets/dist/js/adminlte.min.js') }}"></script>
<script src="{{ asset('admin-assets/dist/js/demo.js') }}"></script>

@yield('additional-js')

Modules/Admin/Resources/views/layouts/includes/menubar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('admin.dashboard') }}" class="brand-link">
        <img src="{{ asset('front-assets/images/xm-logo.png') }}" alt="AdminLTE Logo"
            class="brand-image" style="margin-top: 0px;">
        <span class="brand-text font-weight-light"><strong>{{ config('app.name', 'Laravel') }}</strong></span>
    </a>

    @php
        $crName = \Request::route()->getName();
    @endphp
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">

                {{-- dashboard link --}}
                <li class="nav-item">
                    <a href="{{ route('admin.dashboard') }}" class="nav-link {{ getActiveClass($crName, ['admin.dashboard']) }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                {{-- logout link --}}
                <li class="nav-item">
                    <a href="{{ route('admin.logout') }}" class="nav-link">
                        <i class="nav-icon fas fa-power-off"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

Modules/Admin/Resources/views/layouts/includes/top-layout.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link font-weight-bold" data-toggle="dropdown" href="#">{{ XI_ADMIN()->name }}</a>
            <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
                <a href="{{ route('admin.profile') }}" class="dropdown-item">
                    <i class="fa fa-user mr-2"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('admin.logout') }}" class="dropdown-item">
                    <i class="fa fa-power-off mr-2"></i> Log Out
                </a>
            </div>
        </li>
    </ul>
</nav>

Modules/Admin/Resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ env('APP_NAME') }} - Admin | @yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @include('admin::layouts.includes.css')
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        @include('admin::layouts.includes.top-layout')

        @include('admin::layouts.includes.menubar')

        <div class="content-wrapper">
            @yield('page-header')
            
            @yield('page-content')
        </div>

        @include('admin::layouts.includes.bottom-layout')
    </div>

    @include('admin::layouts.includes.javascript')
</body>

</html>

Modules/Admin/Resources/views/layouts/master_auth.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ env('APP_NAME') }} | Admin - @yield('title')</title>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin-assets/dist/css/adminlte.min.css') }}">
</head>

@yield('admin-auth-body')

<!-- jQuery -->
<script src="{{ asset('admin-assets/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin-assets/dist/js/adminlte.min.js') }}"></script>

</html>

Modules/Admin/Resources/views/users/profile.blade.php
@extends('admin::layouts.master')

@section('title', 'Profile')

@section('page-header')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Profile</h1>
            </div>
        </div>
    </div>
</section>
@endsection

@section('page-content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-9 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">Personal Info</div>
                    <div class="card-body">
                        <form id="UserPersonalDetails" class="form" action="{{ url('/UpdatePersonalInfo') }}"
                            method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-12 col-xs-12 col-12">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" id="name" name="name" class="form-control"
                                            placeholder="Your Name" value="{{ XI_ADMIN()->name }}" required>
                                        @error('name')
                                            <span class="text-danger" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-12">
                                    <button type="submit" class="btn btn-primary"> Save </button>
                                    <a href="{{ route('admin.dashboard') }}" class="btn btn-outline-primary"
                                        style="border: 1px solid #3097d1">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-9 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">Update Password</div>
                    <div class="card-body">
                        <form id="UserPassword" class="form" action="{{ url('/UpdatePassword') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-12 col-xs-12 col-12">
                                    <div class="form-group">
                                        <label for="current_password">Current Password</label>
                                        <input type="password" id="current_password" name="current_password"
                                            class="form-control" placeholder="Current Password" value="" required>
                                        @error('current_password')
                                            <span class="text-danger" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-12 col-xs-12 col-12">
                                    <div class="form-group">
                                        <label for="new_password">New Password</label>
                                        <input type="password" id="new_password" name="new_password"
                                            class="form-control" placeholder="New Password" value="" required>
                                        @error('confirm_password')
                                            <span class="text-danger" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-12 col-xs-12 col-12">
                                    <div class="form-group">
                                        <label for="confirm_password">Confirm Password</label>
                                        <input type="password" id="confirm_password" name="confirm_password"
                                            class="form-control" placeholder="Confirm Password" value="" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-12">
                                    <button type="submit" class="btn btn-primary"> Save </button>
                                    <a href="{{ route('admin.dashboard') }}" class="btn btn-outline-primary"
                                        style="border: 1px solid #3097d1">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection